### ISSUE TITLE
Update prelude for new Builtins module

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/agda-prelude#11]

**Comment by scott-fleischman** [comment]
I took a brief look at this since I've started using the Agda.Builtin modules in my own project and was looking at using this prelude.

One problem is that the [Agda.Builtin Bool](https://github.com/agda/agda/blob/d76b3920f20624ee630f1a90ad69ce97d2a386db/src/data/lib/prim/Agda/Builtin/Bool.agda) isn't parameterized by a level.

How would you like to move forward with this library? It doesn't seem like this prelude itself uses the higher-level bools but I'm not sure how it's used elsewhere.

I thought of using only a subset of Agda.Builtin modules. However that doesn't work well because they often reference other Builtin modules. For example, some of the other Agda.Builtin modules (Char, Float, Nat, etc.) reference Agda.Builtin.Bool.

**Comment by freebroccolo** [comment]
I don't think it's critical that `Bool` be parameterized by a level. To be honest, I have only used that maybe once or twice. I'm fine with dropping it for compatibility with the builtins module. If it matters, the workaround would be to use `Bool` under the structure in the `Lift` module.
