### ISSUE TITLE
Add non-sized versions of List, Stream?

### ISSUE THREAD

**Issue by jonsterling** [freebroccolo/agda-prelude#6]
[Related to [this thread](https://github.com/jonsterling/agda-bar-induction/commit/e5b896ae9cecef35f9dc18ffe472293079b1ef68#commitcomment-15493325)].

I'm finding that it would be useful to have plain versions of these types, since it is very easy to get into a situation where I cannot use equational reasoning (or, seem to be unable to do so).

**Comment by freebroccolo** [comment]
I think it's probably worth doing this for the inductive types like `List` and `Vec`. We should probably also have heterogeneous equality. For the coinductive types, I'm not sure it will be very useful since equational reasoning with the identity type already isn't going to work very well. I have started providing bisimulation relations for some of these.

**Comment by jonsterling** [comment]
@freebroccolo Ah, good point!
